SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `meteocal` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `meteocal`;

CREATE TABLE IF NOT EXISTS `CALENDAR` (
  `EVENT` bigint(20) NOT NULL,
  `USER_` varchar(255) NOT NULL,
  `INVITE_STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`EVENT`,`USER_`),
  KEY `FK_CALENDAR_USER_` (`USER_`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `CONTACT` (
  `EMAIL` varchar(255) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `SURNAME` varchar(255) DEFAULT NULL,
  `OWNER` varchar(255) NOT NULL,
  PRIMARY KEY (`EMAIL`,`OWNER`),
  KEY `FK_CONTACT_OWNER` (`OWNER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `EVENT` (
  `ID` bigint(20) NOT NULL,
  `BEGIN_TIME` datetime DEFAULT NULL,
  `BWODB` tinyint(1) DEFAULT '0',
  `BWTDB` tinyint(1) DEFAULT '0',
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `END_TIME` datetime DEFAULT NULL,
  `LOCATION` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `OUTDOOR` tinyint(1) DEFAULT '0',
  `PUBLIC_` tinyint(1) DEFAULT '0',
  `CREATOR` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_EVENT_CREATOR` (`CREATOR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SEQUENCE` (
  `SEQ_NAME` varchar(50) NOT NULL,
  `SEQ_COUNT` decimal(38,0) DEFAULT NULL,
  PRIMARY KEY (`SEQ_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `SEQUENCE` (`SEQ_NAME`, `SEQ_COUNT`) VALUES
('SEQ_GEN', 0);

CREATE TABLE IF NOT EXISTS `TOKEN` (
  `TOKEN` varchar(255) NOT NULL,
  `STATUS` tinyint(1) DEFAULT '0',
  `TIME_` datetime DEFAULT NULL,
  `USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TOKEN`),
  KEY `FK_TOKEN_USER` (`USER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `UPDATE_` (
  `EVENT` bigint(20) NOT NULL,
  `RECIPIENT` varchar(255) NOT NULL,
  `UPDATE_NUMBER` bigint(20) NOT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `READ_` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`EVENT`,`RECIPIENT`,`UPDATE_NUMBER`),
  KEY `FK_UPDATE__RECIPIENT` (`RECIPIENT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `USERS` (
  `EMAIL` varchar(255) NOT NULL,
  `GROUPNAME` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `PUBLIC_` tinyint(1) DEFAULT '0',
  `SURNAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `WEATHER_CONDITION` (
  `TIME_` date NOT NULL,
  `CODE` int(11) DEFAULT NULL,
  `OLD_CODE` int(11) DEFAULT NULL,
  `TEMPERATURE` int(11) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  `EVENT` bigint(20) NOT NULL,
  PRIMARY KEY (`TIME_`,`EVENT`),
  KEY `FK_WEATHER_CONDITION_EVENT` (`EVENT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `CALENDAR`
  ADD CONSTRAINT `FK_CALENDAR_EVENT` FOREIGN KEY (`EVENT`) REFERENCES `EVENT` (`ID`),
  ADD CONSTRAINT `FK_CALENDAR_USER_` FOREIGN KEY (`USER_`) REFERENCES `USERS` (`EMAIL`);

ALTER TABLE `CONTACT`
  ADD CONSTRAINT `FK_CONTACT_OWNER` FOREIGN KEY (`OWNER`) REFERENCES `USERS` (`EMAIL`);

ALTER TABLE `EVENT`
  ADD CONSTRAINT `FK_EVENT_CREATOR` FOREIGN KEY (`CREATOR`) REFERENCES `USERS` (`EMAIL`);

ALTER TABLE `TOKEN`
  ADD CONSTRAINT `FK_TOKEN_USER` FOREIGN KEY (`USER`) REFERENCES `USERS` (`EMAIL`);

ALTER TABLE `UPDATE_`
  ADD CONSTRAINT `FK_UPDATE__RECIPIENT` FOREIGN KEY (`RECIPIENT`) REFERENCES `USERS` (`EMAIL`),
  ADD CONSTRAINT `FK_UPDATE__EVENT` FOREIGN KEY (`EVENT`) REFERENCES `EVENT` (`ID`);

ALTER TABLE `WEATHER_CONDITION`
  ADD CONSTRAINT `FK_WEATHER_CONDITION_EVENT` FOREIGN KEY (`EVENT`) REFERENCES `EVENT` (`ID`);


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
